A3_MiBank_App/Models/Account.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;




namespace A3_MiBank_App.Models
{

        public enum AccountType
        {
            Checking = 1,
            Savings = 2
        }

        public class Account
        {

            [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
            [Range(1000,9999)]
            [Display(Name = "Account Number")]
            public int AccountNumber { get; set; }

            [Display(Name = "Type")]    
            [Required,MinLength(1),MaxLength(8)]
            public AccountType AccountType { get; set; }

            [Required]
            public int CustomerID { get; set; }
            public virtual Customer Customer { get; set; }

            [Range(0,99999999999999)]
            [DataType(DataType.Currency)]
            [Column(TypeName = "money")]
            //[Column(TypeName = "money")]
            public decimal Balance { get; set; }   // ?is this required  

            [Required, DataType(DataType.DateTime)]
            [DisplayFormat(DataFormatString = "{dd/MM/yyyy HH:mm:ss}")]
            public DateTime ModifyDate { get; set; }

            [Display(Name = "Destination Account No")]
            public int DestinationAccountNumber { get; set; }

        // a NAVIGATION PROPERTY
        [JsonIgnore]
        public virtual List<Transaction> Transactions { get; set; } // forms 1-many relationship
        [JsonIgnore]
        public virtual List<BillPay> BillPays { get; set; }
    }
    
    
}

A3_MiBank_App/ViewModels/BillPayDisplayViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using A3_MiBank_App.Models;
using X.PagedList;


namespace A3_MiBank_App.ViewModels
{
    public class BillPayDisplayViewModel
    {
        public int BillPayID { get; set; }

        public int AccountNumber { get; set; }
        public Account Account { get; set; }
        public AccountType AccountType { get; set; }

        public decimal Amount { get; set; }
        public decimal Balance { get; set; }

        public int PayeeID { get; set; }
        public Payee Payee { get; set; }

        
        public string PayeeName { get; set; }

        public DateTime ScheduleDate { get; set; }
        public int Period { get; set; }
        public DateTime ModifyDate { get; set; }

        public IPagedList<BillPay> PagedBillPayList { get; internal set; }
    }
}

A3_MiBank_App/ViewModels/StatementViewModel.cs
using System;
using System.Globalization;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using A3_MiBank_App.Models;
using X.PagedList;

namespace A3_MiBank_App.ViewModels
{
    public class StatementViewModel
    {
        
        public int AccountNumber { get; set; }

        public Account Account { get; set; }
        public int DestinationAccount { get; set; }

        [DisplayFormat(DataFormatString = "{0:C2}")]
        public decimal Amount { get; set; }

        public string Comment { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}")]
        public DateTime ModifyDate { get; set; }

        public IPagedList<Transaction> PagedTransactionsList { get; internal set; }

        
    }
}

A3_MiBank_App/Controllers/BillPayController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using A3_MiBank_App.Data;
using A3_MiBank_App.Models;
using System.Globalization;
using A3_MiBank_App.ViewModels;
using A3_MiBank_App.Utilities;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;

namespace A3_MiBank_App.Controllers
{
    public class BillPayController : Controller
    {
        private readonly MiBankContext _context;
        BillPay _billPay = new BillPay();
        public decimal[] ServiceCharge = { 0.1M, 0.2M };
        public CultureInfo _culture = new CultureInfo("en-au");

        public BillPayController(MiBankContext context)
        {
            _context = context;
          
        }



        //BILLPAY - GET --> accountNo into ViewModel
        [HttpGet]
        public async Task<IActionResult> BillPay()
        {

            var customerID = HttpContext.Session.GetInt32(nameof(Customer.CustomerID));
            var AccountsList = await _context.Accounts.Where(a => a.CustomerID == customerID).ToListAsync();

            return View(
                new BillPayViewModel
                {
                    AccountNumbersList = AccountsList.Select(a =>
                                  new SelectListItem
                                  {
                                      Value = a.AccountNumber.ToString(),
                                      Text = a.AccountNumber.ToString() + " " + a.AccountType.ToString() + " : Balance " + a.Balance.ToString("C2", _culture),
                                  }).ToList(),
                    ScheduleDate = DateTime.UtcNow.ToLocalTime(),
                    PayeeNameOptions = _context.Payees.Select(p =>
                                  new SelectListItem
                                  {
                                      Value = p.PayeeName.ToString(),
                                      Text = p.PayeeName
                                  }).ToList(),
                    ModifyDate = DateTime.UtcNow.ToLocalTime()
                });
        }



        //BILLPAY - POST --> BillPayViewModel into View
        [HttpPost]
        public async Task<IActionResult> BillPay(BillPayViewModel viewModel)
        {
            // get Account
            viewModel.Account = await _context.Accounts.FindAsync(viewModel.AccountNumber);
            // assign current balance
            viewModel.Balance = viewModel.Account.Balance;
            viewModel.AccountType = viewModel.Account.AccountType;

            // assign the payee ID of the PayeeName chosen by the user
            Payee payee = _context.Payees.FirstOrDefault(p => p.PayeeName == viewModel.PayeeName);
            viewModel.PayeeID = payee.PayeeID;


            if (viewModel.Amount <= 0 || viewModel.Amount > 99999999999999)
            {
                ModelState.AddModelError(nameof(viewModel.Amount), "Amount must be more than 0, and less than 99,999,999,999,999.");
                RefreshBillPayOnError(viewModel);
                return View(viewModel);
            }
            if (viewModel.Amount.HasMoreThanTwoDecimalPlaces())
            {
                ModelState.AddModelError(nameof(viewModel.Amount), "Amount cannot have more than 2 decimal places.");
                RefreshBillPayOnError(viewModel);
                return View(viewModel);
            }
            if (!_billPay.HasSufficientFunds(viewModel.AccountType, viewModel.Balance, viewModel.Amount, ServiceCharge[1]))
            {
                ModelState.AddModelError(nameof(viewModel.Amount), "Insufficient Funds. Minimum Balance Required for: Checking $200, Savings $0.");
                RefreshBillPayOnError(viewModel);
                return View(viewModel);
            }

            _billPay.ScheduleBillPay(viewModel, ServiceCharge[1], _context);

            await _context.SaveChangesAsync();

            return RedirectToAction("CustomerAccounts", "Customers");

        }

        // ADD ANOTHER YEAR TO ANNUAL PAYMENT
        internal void AddAnotherYearBillPay(BillPay billPay)
        {
            _billPay.AddAnotherYearBillPay(billPay);
        }

        // ADD ANOTHER QUARTER TO QUARTERLY PAYMENT
        internal void AddAnotherQuarterBillPay(BillPay billPay)
        {
            _billPay.AddAnotherQuarterBillPay(billPay);
        }

        // ADD ANOTHER MINUTE TO MUNUTELY PAYMENT
        internal void AddAnotherMinuteBillPay(BillPay billPay)
        {
            _billPay.AddAnotherMinuteBillPay(billPay);
        }


        //BILLPAY - GET --> MODIFY BillPayID into ViewModel
        [HttpGet]
        public async Task<IActionResult> ModifyBillPay(int billPayID)
        {
            var billPayList = await _context.BillPay.Where(b => b.BillPayID == billPayID).ToListAsync();
            BillPay billPay = billPayList.Find(b => b.BillPayID == billPayID);
            int accountNumber = billPay.AccountNumber;

            var customerID = HttpContext.Session.GetInt32(nameof(Customer.CustomerID));
            var AccountsList = await _context.Accounts.Where(a => a.CustomerID == customerID).ToListAsync();

            Account account = _context.Accounts.FirstOrDefault(a => a.AccountNumber == accountNumber);
            AccountType accountType = account.AccountType;

            Payee payee = _context.Payees.FirstOrDefault(p => p.PayeeID == billPay.PayeeID);


            return View(new BillPayViewModel
            {
                BillPayID = billPayID,
                AccountNumber = accountNumber,
                AccountNumbersList = AccountsList.Select(a =>
                              new SelectListItem
                              {
                                  Value = a.AccountNumber.ToString(),
                                  Text = a.AccountNumber.ToString() + " " + a.AccountType.ToString() + " : Balance " + a.Balance.ToString("C2", _culture)
                              }).ToList(),
                PayeeNameOptions = _context.Payees.Select(p =>
                              new SelectListItem
                              {
                                  Value = p.PayeeName.ToString(),
                                  Text = p.PayeeName
                              }).ToList(),
                ModifyDate = DateTime.Now.ToLocalTime(),
                Account = account,
                AccountType = accountType,
                Amount = billPay.Amount,
                Balance = account.Balance,
                PayeeID = payee.PayeeID,
                PayeeName = payee.PayeeName,
                Payee = payee,
                ScheduleDate = billPay.ScheduleDate.ToLocalTime(),
                Period = billPay.PaymentPeriod,
                Paid = false
            });
        }


        // POST --> MODIFY BILLPAY
        [HttpPost]
        public async Task<IActionResult> ModifyBillPay([Bind] BillPayViewModel viewModel)
        {

            // get Account
            viewModel.Account = await _context.Accounts.FindAsync(viewModel.AccountNumber);
            // assign current balance
            viewModel.Balance = viewModel.Account.Balance;

            //get BillPay
            var billPay = await _context.BillPay.FirstOrDefaultAsync(b => b.BillPayID == viewModel.BillPayID);


            // assign the payee ID of the PayeeName chosen by the user
            Payee payee = _context.Payees.FirstOrDefault(p => p.PayeeName == viewModel.PayeeName);
            viewModel.PayeeID = payee.PayeeID;


            if (viewModel.Amount <= 0 || viewModel.Amount > 99999999999999)
            {
                ModelState.AddModelError(nameof(viewModel.Amount), "Amount must be more than 0, and less than 99,999,999,999,999.");
                RefreshBillPayOnError(viewModel);
                return View(viewModel);
            }
            if (viewModel.Amount.HasMoreThanTwoDecimalPlaces())
            {
                ModelState.AddModelError(nameof(viewModel.Amount), "Amount cannot have more than 2 decimal places.");
                RefreshBillPayOnError(viewModel);
                return View(viewModel);
            }
            if (!_billPay.HasSufficientFunds(viewModel.AccountType, viewModel.Balance, viewModel.Amount, ServiceCharge[1]))
            {
                ModelState.AddModelError(nameof(viewModel.Amount), "Insufficient Funds. Minimum Balance Required for: Checking $200, Savings $0.");
                RefreshBillPayOnError(viewModel);
                return View(viewModel);
            }

            billPay.BillPayID = viewModel.BillPayID;
            billPay.Amount = viewModel.Amount;
            billPay.AccountNumber = viewModel.AccountNumber;
            billPay.ModifyDate = DateTime.UtcNow;
            billPay.PayeeID = viewModel.PayeeID;
            billPay.PaymentPeriod = viewModel.Period;
            billPay.ScheduleDate = viewModel.ScheduleDate;
            billPay.Account = viewModel.Account;
            billPay.Payee = viewModel.Payee;
            billPay.Paid = false;


            Console.WriteLine(billPay.BillPayID);
            Console.WriteLine(billPay.Amount);
            Console.WriteLine(billPay.AccountNumber);
            Console.WriteLine(billPay.ModifyDate);
            Console.WriteLine(billPay.PayeeID);
            Console.WriteLine(billPay.PaymentPeriod.ToString());
            Console.WriteLine(billPay.ScheduleDate);
            Console.WriteLine(billPay.Account);
            Console.WriteLine(billPay.Payee);

            //  UPDATE DATABASE WITH MODIFIED RECORD

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(billPay);

A3_MiBank_App/Views/Accounts/BillPayDisplay.cshtml
@using Microsoft.AspNetCore.Http;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;
@using System.Globalization;


@model A3_MiBank_App.ViewModels.BillPayDisplayViewModel

@{
    ViewData["Title"] = "Future Scheduled Bill Pays";
    CultureInfo culture = new CultureInfo("en-au");
   
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
</head>
    <body>

    <h3>@ViewData["Title"]</h3>
    <h4>Customer:  @Context.Session.GetString(nameof(Customer.CustomerName))</h4>
    <br />

    <div class="form-background">

        <h4>Account: @Html.DisplayFor(x => x.Account.AccountNumber)</h4>
        <h4>Balance: @Model.Account.Balance.ToString("C2",culture)</h4>
        <table class="table">
            <tr>
                <th>@Html.DisplayNameFor(x => x.Account.BillPays[0].BillPayID)</th>
                <th>@Html.DisplayNameFor(x => x.Account.BillPays[0].AccountNumber)</th>
                <th>@Html.DisplayNameFor(x => x.Account.BillPays[0].PayeeID)</th>
                <th>@Html.DisplayNameFor(x => x.Account.BillPays[0].Amount)</th>
                <th>@Html.DisplayNameFor(x => x.Account.BillPays[0].ScheduleDate)</th>
                <th>@Html.DisplayNameFor(x => x.Account.BillPays[0].PaymentPeriod)</th>
                <th>@Html.DisplayNameFor(x => x.Account.BillPays[0].ModifyDate)</th>
                <th>@Html.DisplayNameFor(x => x.Account.BillPays[0].Paid)</th>

            </tr>

            @foreach (var billpay in Model.PagedBillPayList)
            {
        <tr>

            <td>@Html.DisplayFor(x => billpay.BillPayID)</td>
            <td>@Html.DisplayFor(x => billpay.AccountNumber)</td>
            <td>@Html.DisplayFor(x => billpay.Payee.PayeeName)</td>
            <td>@billpay.Amount.ToString("C2", culture)</td>
            <td>@Html.FormatValue(billpay.ScheduleDate, "{0:dd/MM/yyyy HH:mm:ss}")</td>
            <!--<td>@billpay.ScheduleDate.ToLocalTime()</td>-->
            <td>@Html.DisplayFor(x => billpay.PaymentPeriod)</td>
            <td>@Html.FormatValue(billpay.ModifyDate, "{0:dd/MM/yyyy HH:mm:ss}")</td>
            <!--<td>@billpay.ScheduleDate.ToLocalTime()</td>-->
            <td>@Html.DisplayFor(x => billpay.Paid)</td>

            <td>
                <form asp-action="ModifyBillPay" asp-controller="BillPay" method="get">
                    <input type="hidden" name="BillPayID" value="@billpay.BillPayID" />
                    <input type="submit" class="btn btn-primary" value="Modify" />
                </form>
            </td>

        </tr>
            }
        </table>

        <div style="float: right">
            <a asp-controller="Customers" asp-action="CustomerAccounts">Back to Accounts</a>
        </div>

        @Html.PagedListPager(Model.PagedBillPayList, page => Url.Action("BillPayDisplay", new { page }),
                        new PagedListRenderOptionsBase
                        {
                            LiElementClasses = new[] { "page-item" },
                            PageClasses = new[] { "page-link" }
                        }

                    )
    </div>

</body>
</html>

A3_MiBank_App/Views/Accounts/Create.cshtml
@model A3_MiBank_App.Models.Account

@{
    //Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <div class="text-center">
        <h1 class="display-4">Create Account</h1>
    </div>
    <h4>Account</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="AccountNumber" class="control-label"></label>
                    <input asp-for="AccountNumber" class="form-control" />
                    <span asp-validation-for="AccountNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AccountType" class="control-label"></label>
                    <select asp-for="AccountType" class="form-control"></select>
                    <span asp-validation-for="AccountType" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CustomerID" class="control-label"></label>
                    <select asp-for="CustomerID" class="form-control" asp-items="ViewBag.CustomerID"></select>
                </div>
                <div class="form-group">
                    <label asp-for="Balance" class="control-label"></label>
                    <input asp-for="Balance" class="form-control" />
                    <span asp-validation-for="Balance" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ModifyDate" class="control-label"></label>
                    <input asp-for="ModifyDate" class="form-control" />
                    <span asp-validation-for="ModifyDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DestinationAccountNumber" class="control-label"></label>
                    <input asp-for="DestinationAccountNumber" class="form-control" />
                    <span asp-validation-for="DestinationAccountNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</body>
</html>

A3_MiBank_App/Views/Accounts/Delete.cshtml
@model A3_MiBank_App.Models.Account

@{
    //Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Account</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccountType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccountType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.CustomerName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Balance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Balance)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifyDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifyDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DestinationAccountNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DestinationAccountNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AccountNumber" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

A3_MiBank_App/Views/Accounts/Statement.cshtml
@using Microsoft.AspNetCore.Http;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;
@using System.Globalization;



@model A3_MiBank_App.ViewModels.StatementViewModel

@{
    ViewData["Title"] = "Statement";
    CultureInfo culture = new CultureInfo("en-au");

 }

<!DOCTYPE html>
<html lang="en-au">
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Statement</title>
    </head>
    <body>

        <h3>@ViewData["Title"]</h3>
        <h4>Customer:  @Context.Session.GetString(nameof(Customer.CustomerName))</h4>
        <br />
        <div class="form-background">

            <h5><span style="margin-right: 50px;"><b>Account:</b> @Html.DisplayFor(x => x.Account.AccountNumber)</span><span><b>Balance:</b>@Model.Account.Balance.ToString("C2",culture)</span></h5>

            <table class="table">
                <tr>
                    <th>@Html.DisplayNameFor(x => x.Account.Transactions[0].TransactionID)</th>
                    <th>@Html.DisplayNameFor(x => x.Account.Transactions[0].TransactionType)</th>
                    <th>@Html.DisplayNameFor(x => x.Account.Transactions[0].AccountNumber)</th>
                    <th>@Html.DisplayNameFor(x => x.Account.Transactions[0].DestinationAccountNumber)</th>
                    <th>@Html.DisplayNameFor(x => x.Account.Transactions[0].Amount)</th>
                    <th>@Html.DisplayNameFor(x => x.Account.Transactions[0].Comment)</th>
                    <th>@Html.DisplayNameFor(x => x.Account.Transactions[0].ModifyDate)</th>

                </tr>

                @foreach (var transaction in Model.PagedTransactionsList)
                {
            <tr>

                <td>@Html.DisplayFor(x => transaction.TransactionID)</td>
                <td>@Html.DisplayFor(x => transaction.TransactionType)</td>
                <td>@Html.DisplayFor(x => transaction.AccountNumber)</td>
                <td>@Html.DisplayFor(x => transaction.DestinationAccountNumber)</td>
                <td>@transaction.Amount.ToString("C2", culture)</td>
                <td>@Html.DisplayFor(x => transaction.Comment)</td>
                <!--<td>@transaction.ModifyDate.ToLocalTime()</td>-->
                <td>@Html.FormatValue(transaction.ModifyDate, "{0:dd/MM/yyyy HH:mm:ss}")</td>


            </tr>
                }
            </table>

            <div style="float: right">
                <a asp-controller="Customers" asp-action="CustomerAccounts">Back to Accounts</a>
            </div>

            @Html.PagedListPager(Model.PagedTransactionsList, page => Url.Action("Statement", new { page }),
                        new PagedListRenderOptionsBase
                        {
                            LiElementClasses = new[] { "page-item" },
                            PageClasses = new[] { "page-link" }
                        }

                    )

            
        </div>
    </body>
    </html>